import { nextConfig } from '@repo/config/eslint/next';

const config = [
  ...nextConfig({ tsconfigRootDir: import.meta.dirname }),
  {
    // shadcn/ui primitives are generated by `shadcn add`; kept close to upstream so they can be re-synced.
    files: ['src/components/ui/**'],
    rules: { '@typescript-eslint/explicit-module-boundary-types': 'off' },
  },
];

export default config;
