import { z } from 'zod';

import { CountryCode, CurrencyCode, Locale, TimeZone } from '../common/primitives.js';

/** Tenant lifecycle (06 "Tenant lifecycle"). */
export const TenantStatus = z.enum(['ACTIVE', 'SUSPENDED', 'CLOSED']);
export type TenantStatus = z.infer<typeof TenantStatus>;

/**
 * Platform-wide unique, lowercase, 3–63 chars of letters, digits and inner hyphens (future subdomain); immutable.
 * Mirrors the `tenants_slug_format_check` constraint.
 */
export const TenantSlug = z
  .string()
  .regex(
    /^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$/,
    'Must be 3–63 lowercase letters, digits or hyphens, not starting or ending with a hyphen.',
  );
export type TenantSlug = z.infer<typeof TenantSlug>;

const text = (max: number) => z.string().trim().min(1).max(max);

/** Company profile fields that can be edited after creation (not slug, not base currency). */
const profileFields = {
  name: text(200),
  legalName: text(200).nullable(),
  timezone: TimeZone,
  locale: Locale,
  countryCode: CountryCode.nullable(),
  taxId: text(64).nullable(),
  addressLine1: text(200).nullable(),
  addressLine2: text(200).nullable(),
  city: text(100).nullable(),
  region: text(100).nullable(),
  postalCode: text(20).nullable(),
  phone: text(32).nullable(),
  email: z.email().max(254).nullable(),
};

/**
 * Provisioning a tenant (setup wizard, SaaS signup, platform admin — session 8). The tenant id is generated by the
 * server, never supplied. Base currency is fixed at creation (tenant-management.md "Business rules").
 */
export const CreateTenantInput = z.strictObject({
  name: profileFields.name,
  slug: TenantSlug,
  baseCurrency: CurrencyCode,
  timezone: profileFields.timezone,
  locale: profileFields.locale,
  legalName: profileFields.legalName.optional(),
  countryCode: profileFields.countryCode.optional(),
  taxId: profileFields.taxId.optional(),
  addressLine1: profileFields.addressLine1.optional(),
  addressLine2: profileFields.addressLine2.optional(),
  city: profileFields.city.optional(),
  region: profileFields.region.optional(),
  postalCode: profileFields.postalCode.optional(),
  phone: profileFields.phone.optional(),
  email: profileFields.email.optional(),
});
export type CreateTenantInput = z.infer<typeof CreateTenantInput>;

/** Partial profile update; `null` clears an optional field. */
export const TenantProfilePatch = z.strictObject({
  name: profileFields.name.optional(),
  legalName: profileFields.legalName.optional(),
  timezone: profileFields.timezone.optional(),
  locale: profileFields.locale.optional(),
  countryCode: profileFields.countryCode.optional(),
  taxId: profileFields.taxId.optional(),
  addressLine1: profileFields.addressLine1.optional(),
  addressLine2: profileFields.addressLine2.optional(),
  city: profileFields.city.optional(),
  region: profileFields.region.optional(),
  postalCode: profileFields.postalCode.optional(),
  phone: profileFields.phone.optional(),
  email: profileFields.email.optional(),
});
export type TenantProfilePatch = z.infer<typeof TenantProfilePatch>;
